from objects.receipe import Recipe

recipes = [
    Recipe("Sauerbraten",
           "Sauerbraten is a traditional German pot roast, known for its savory and tangy flavor. The beef is marinated in a mixture of vinegar, water, and various spices for several days, imparting a distinctive taste to the dish. Slow-cooked to perfection, it's typically served with red cabbage and potato dumplings, making it a hearty and flavorful meal.",
           "",
           "",
           []),

    Recipe("Spaghetti Bolognese",
           "Spaghetti Bolognese is a classic Italian pasta dish. It features a rich and savory meat sauce served over cooked spaghetti. Garnish with grated Parmesan cheese and fresh basil for a delicious meal.",
           "",
           "",
           []),
    Recipe("Paella Valenciana",
           "Paella Valenciana is a classic Spanish dish originating from Valencia. This vibrant and aromatic one-pan rice dish features a delightful combination of saffron-infused rice, rabbit or chicken, green beans, and snails. Cooked in a wide, shallow pan, paella is often prepared and enjoyed as a communal meal, bringing people together to savor the rich flavors of Spanish cuisine.",
           "",
           "",
           []),
    Recipe("Fish and Chips",
           "Fish and Chips is an iconic British dish that has stood the test of time. This simple yet satisfying recipe consists of battered and fried fish, usually cod or haddock, served with thick-cut fries. Traditionally enjoyed with malt vinegar and tartar sauce, it's a beloved street food that captures the essence of British culinary tradition.",
           "",
           "",
           []),
    Recipe("Sushi Rolls",
           "Sushi Rolls, originating from Japan, are a delicate and artful combination of vinegared rice, fresh fish, and vegetables. Whether it's the classic California Roll, the spicy Tuna Roll, or the elegant Dragon Roll, sushi offers a diverse range of flavors and textures. Served with soy sauce, pickled ginger, and wasabi, sushi is a culinary masterpiece that reflects the precision and craftsmanship of Japanese cuisine.",
           "",
           "",
           []),
    Recipe("Chicken Tikka Masala",
           "Chicken Tikka Masala is a popular Indian dish that combines marinated and roasted chicken with a rich and creamy tomato-based curry sauce. The tender chicken pieces are first marinated in a blend of yogurt and spices, then grilled or baked to perfection. The flavorful sauce, infused with aromatic spices like cumin, coriander, and garam masala, makes this dish a comforting and delicious staple in Indian cuisine.",
           "",
           "",
           []),
    Recipe("Kung Pao Chicken",
           "Kung Pao Chicken is a classic Chinese stir-fry dish known for its bold flavors and contrasting textures. Tender chicken is stir-fried with peanuts, vegetables, and chili peppers, creating a harmonious blend of spicy, sweet, and savory. The sauce, made with soy sauce, vinegar, and hoisin sauce, adds depth to the dish. Garnished with green onions and sesame seeds, Kung Pao Chicken is a delightful representation of Sichuan cuisine.",
           "",
           "",
           []),
    Recipe("Coq au Vin",
           "Coq au Vin is a classic French dish that features chicken cooked in red wine with mushrooms, bacon, and onions. The slow-cooking process infuses the dish with rich flavors, creating a comforting and savory meal. It is often served with mashed potatoes or crusty bread to soak up the delicious sauce.",
           "",
           "",
           []),
    Recipe("Pad Thai",
           "Pad Thai is a popular Thai stir-fried noodle dish known for its sweet, sour, and savory flavors. It typically includes rice noodles, shrimp or chicken, bean sprouts, peanuts, and lime. The dish is often garnished with fresh cilantro and a wedge of lime, offering a delightful combination of textures and tastes.",
           "",
           "",
           []),
    Recipe("Goulash",
           "Goulash is a hearty Hungarian stew made with tender beef, onions, peppers, and paprika. This comforting dish is slow-cooked to perfection, allowing the flavors to meld together. It is commonly served with egg noodles or crusty bread.",
           "",
           "",
           []),
    Recipe("Kabsa",
           "Kabsa is a traditional Arabic rice dish that features spiced rice, meat (often chicken, lamb, or beef), and a mixture of aromatic spices. The dish is cooked with tomatoes, dried lime, and other flavor-enhancing ingredients. Kabsa is a staple in Arabian cuisine and is often served during special occasions.",
           "",
           "",
           []),
    Recipe("Falafel",
           "Falafel is a popular Middle Eastern dish made from ground chickpeas or fava beans, herbs, and spices. The mixture is formed into balls or patties and deep-fried until golden brown. Falafel is commonly served in pita bread with tahini sauce, tomatoes, and cucumbers.",
           "",
           "",
           []),
    Recipe("Pierogi",
           "Pierogi are traditional Ukrainian dumplings filled with various ingredients, such as potatoes, cheese, meat, or fruit. They are typically boiled and then pan-fried for a crispy exterior. Pierogi can be served as a savory main dish or a sweet dessert, depending on the filling.",
           "",
           "",
           []),
    Recipe("Shawarma",
           "Shawarma is a popular Middle Eastern street food made by stacking seasoned meat (often lamb, chicken, or beef) on a vertical rotisserie. The meat is slowly roasted and shaved off to create thin slices. Shawarma is typically served in flatbread with garlic sauce, tahini, and vegetables.",
           "",
           "",
           []),
    Recipe("Stuffed Grape Leaves",
           "Stuffed grape leaves, also known as Dolma, are a delicious Mediterranean dish. Grape leaves are filled with a mixture of rice, pine nuts, and herbs, creating a flavorful and aromatic appetizer. They are often served with a side of yogurt sauce.",
           "",
           "",
           []),
    Recipe("Spicy Tofu Stir-Fry",
           "Spicy tofu stir-fry is a versatile and flavorful dish inspired by Asian cuisine. Cubes of tofu are stir-fried with a medley of colorful vegetables and tossed in a spicy sauce made with soy sauce, ginger, and garlic. Serve over rice or noodles for a satisfying meal.",
           "",
           "",
           []),
    Recipe("Mango Salsa",
           "Mango salsa is a refreshing and tropical condiment that adds a burst of flavor to any dish. It combines diced mango, red onion, cilantro, lime juice, and a hint of jalapeño for a sweet and spicy kick. Enjoy it with grilled chicken, fish, or as a topping for tacos.",
           "",
           "",
           []),
    Recipe("Teriyaki Salmon",
           "Teriyaki salmon is a Japanese-inspired dish that features succulent salmon fillets glazed with a sweet and savory teriyaki sauce. Grilled to perfection, the salmon is served with steamed rice and a side of steamed vegetables for a well-balanced and delicious meal.",
           "",
           "",
           [])




]


recipes_label_extractor = [
    Recipe("Sauerbraten",
           "Sauerbraten is a traditional German pot roast, known for its savory and tangy flavor. The beef is marinated in a mixture of vinegar, water, and various spices for several days, imparting a distinctive taste to the dish. Slow-cooked to perfection, it's typically served with red cabbage and potato dumplings, making it a hearty and flavorful meal.",
           "German",
           "A sauerbraten is a braised roast that has been pre-treated by marinating for several days in a marinade of vinegar and other ingredients. In its various regional variations, it is a well-known traditional dish in German cuisine.",
           []),

    Recipe("Spaghetti Bolognese",
           "Spaghetti Bolognese is a classic Italian pasta dish. It features a rich and savory meat sauce served over cooked spaghetti. Garnish with grated Parmesan cheese and fresh basil for a delicious meal.",
           "Italian",
           "Ragù alla bolognese or ragù bolognese [raˈgu boloɲˈɲeːze] is a minced meat sauce that is mainly combined with pasta. It originates from Bologna in northern Italy, where it is served with egg pasta, preferably tagliatelle. It is also used in other dishes such as lasagne. In French, it is known as bolognaise sauce and worldwide outside Italy in the combination spaghetti bolognese.",
           []),
    Recipe("Paella Valenciana",
           "Paella Valenciana is a classic Spanish dish originating from Valencia. This vibrant and aromatic one-pan rice dish features a delightful combination of saffron-infused rice, rabbit or chicken, green beans, and snails. Cooked in a wide, shallow pan, paella is often prepared and enjoyed as a communal meal, bringing people together to savor the rich flavors of Spanish cuisine.",
           "Spanish",
           "Paella, or also arroz a la paella, (from the Valencian paella, which means 'pan' and refers to the container with which the recipe is made and which gives it its name, and this in turn from the Latin patella) is a rice-based cooking recipe, originating in what is now the Valencian Community, now very popular throughout Spain and served in restaurants all over the world. In this recipe, rice is cooked together with other foods in a pan, generally wide and with handles. The name paella refers both to the recipe or dish cooked and to the container used for its preparation, although the latter is also called paellera, a term originally considered incorrect but which has become accepted in Spanish with use. It is a dish of humble origin, first described in Spain in the Albufera area of Valencia. The popularity of this dish has meant that, at present, it has expanded with a large number of variants adapted in ingredients to the various regions of Spanish cuisine. Paella has become one of the icons of Spanish gastronomy. On November 2021 it was declared an Asset of Cultural Interest. The variety of ingredients makes it to be called with the appellative of baroque preparation by the final arrangement in the presentation. Its popularity grew so much throughout the twentieth century internationally that today it is a dish that can be found in restaurants in the West. This popularity has meant that paella has undergone transformations since the original Valencian paella recipe (a concept subject to much discussion) and variants have appeared that can be summarized as paella marinera, made with a combination of fish and/or seafood; paella mixta; sometimes also called sea and mountain, which consists of a mixture of meat and seafood (or fish) and paella de montaña, which incorporates different products typical of each region such as ribs, rabbit and chicken.",
           []),
    Recipe("Fish and Chips",
           "Fish and Chips is an iconic British dish that has stood the test of time. This simple yet satisfying recipe consists of battered and fried fish, usually cod or haddock, served with thick-cut fries. Traditionally enjoyed with malt vinegar and tartar sauce, it's a beloved street food that captures the essence of British culinary tradition.",
           "British",
           "Fish and chips is a hot dish consisting of fried fish in batter, served with chips. The dish originated in England, where these two components had been introduced from separate immigrant cultures; it is not known who combined them. Often considered Britain's national dish, fish and chips is a common takeaway food in numerous other countries, particularly English-speaking and Commonwealth nations. Fish and chip shops first appeared in the UK in the 1860s and by 1910 there were over 25,000 across the UK. By the 1930s there were over 35,000 shops, but by 2009 there were only approximately 10,000. The British government safeguarded the supply of fish and chips during the First World War and again in the Second World War. It was one of the few foods in the UK not subject to rationing during the wars, which further contributed to its popularity",
           []),
    Recipe("Sushi Rolls",
           "Sushi Rolls, originating from Japan, are a delicate and artful combination of vinegared rice, fresh fish, and vegetables. Whether it's the classic California Roll, the spicy Tuna Roll, or the elegant Dragon Roll, sushi offers a diverse range of flavors and textures. Served with soy sauce, pickled ginger, and wasabi, sushi is a culinary masterpiece that reflects the precision and craftsmanship of Japanese cuisine.",
           "Japanese",
           "Sushi is a Japanese dish made from cooled, soured rice, supplemented with ingredients such as raw or smoked fish, raw seafood, nori (dried and roasted seaweed), vegetables, tofu varieties and egg. The composition varies according to type and recipe. Sushi is served in bite-sized pieces and is visually appealing.",
           []),
]
