def create_languages_countries(countries_languages):
    languages_countries = {}

    for country, language in countries_languages.items():
        if language in languages_countries:
            languages_countries[language].append(country)
        else:
            languages_countries[language] = [country]

    return languages_countries


class Country:
    languages_wiki = {
        "English": "en",
        "German": "de",
        "French": "fr",
        "Spanish": "es",
        "Japanese": "ja",
        "Russian": "ru",
        "Latn": "pt",
        "Italian": "it",
        "Chinese": "zh",
        "Persian": "fa",
        "Polish": "pl",
        "Dutch": "nl",
        "Arabic": "ar",
        "Ukrainian": "uk",
        "Hebrew": "he",
        "Turkish": "tr",
        "Indonesian": "id",
        "Czech": "cs",
        "Swedish": "sv",
        "Korean": "ko",
        "Vietnamese": "vi",
        "Hungarian": "hu",
        "Finnish": "fi",
        "Hindi": "hi",
        "Norwegian": "no",
        "Catalan": "ca",
        "Thai": "th",
        "Greek": "el",
        "Bengali": "bn",
        "Romanian": "ro",
        "Serbian": "sr",
        "Danish": "da",
        "Bulgarian": "bg",
        "Malay": "ms",
        "Azerbaijani": "az",
        "Estonian": "et",
        "Slovak": "sk",
        "Armenian": "hy",
        "Uzbek": "uz",
        "Croatian": "hr",
        "Basque": "eu",
        "Slovene": "sl",
        "Lithuanian": "lt",
        "Latvian": "lv",
        "Esperanto": "eo",
        "Belarusian": "be",
        "Urdu": "ur",
        "Kazakh": "kk",
        "Tamil": "ta",
        "Georgian": "ka",
    }
    langid_languages = {
        "af": "Afrikaans",
        "an": "Aragonese",
        "ar": "Arabic",
        "as": "Assamese",
        "az": "Azerbaijani",
        "be": "Belarusian",
        "bg": "Bulgarian",
        "bn": "Bengali",
        "br": "Breton",
        "bs": "Bosnian",
        "ca": "Catalan",
        "cs": "Czech",
        "cy": "Welsh",
        "da": "Danish",
        "de": "German",
        "dz": "Dzongkha",
        "el": "Greek",
        "en": "English",
        "eo": "Esperanto",
        "es": "Spanish",
        "et": "Estonian",
        "eu": "Basque",
        "fa": "Persian",
        "fi": "Finnish",
        "fo": "Faroese",
        "fr": "French",
        "ga": "Irish",
        "gl": "Galician",
        "gu": "Gujarati",
        "he": "Hebrew",
        "hi": "Hindi",
        "hr": "Croatian",
        "ht": "Haitian",
        "hu": "Hungarian",
        "hy": "Armenian",
        "id": "Indonesian",
        "is": "Icelandic",
        "it": "Italian",
        "ja": "Japanese",
        "jv": "Javanese",
        "ka": "Georgian",
        "kk": "Kazakh",
        "km": "Khmer",
        "kn": "Kannada",
        "ko": "Korean",
        "ku": "Kurdish",
        "ky": "Kyrgyz",
        "la": "Latin",
        "lb": "Luxembourgish",
        "lo": "Lao",
        "lt": "Lithuanian",
        "lv": "Latvian",
        "mg": "Malagasy",
        "mk": "Macedonian",
        "ml": "Malayalam",
        "mn": "Mongolian",
        "mr": "Marathi",
        "ms": "Malay",
        "mt": "Maltese",
        "nb": "Burmese",
        "ne": "Nepali",
        "nl": "Dutch",
        "no": "Norwegian",
        "oc": "Occitan",
        "or": "Oriya",
        "pa": "Punjabi",
        "pl": "Polish",
        "ps": "Pashto",
        "pt": "Portuguese",
        "qu": "Quechua",
        "ro": "Romanian",
        "ru": "Russian",
        "rw": "Kinyarwanda",
        "se": "Sinhala",
        "sk": "Slovak",
        "sl": "Slovenian",
        "sq": "Albanian",
        "sr": "Serbian",
        "sv": "Swedish",
        "sw": "Swahili",
        "ta": "Tamil",
        "te": "Telugu",
        "th": "Thai",
        "tl": "Tagalog",
        "tr": "Turkish",
        "ug": "Uighur",
        "uk": "Ukrainian",
        "ur": "Urdu",
        "vi": "Vietnamese",
        "vo": "Volapük",
        "wa": "Walloon",
        "xh": "Xhosa",
        "zh": "Chinese",
        "zu": "Zulu"
    }
    countries_languages = {
        "England": "English",
        "Germany": "German",
        "France": "French",
        "Spain": "Spanish",
        "Japan": "Japanese",
        "Russia": "Russian",
        "Portugal": "Latn",
        "Italy": "Italian",
        "China": "Chinese",
        "Iran": "Persian",
        "Poland": "Polish",
        "Netherlands": "Dutch",
        "Arab World": "Arabic",
        "Ukraine": "Ukrainian",
        "Israel": "Hebrew",
        "Turkey": "Turkish",
        "Indonesia": "Indonesian",
        "Czech Republic": "Czech",
        "Sweden": "Swedish",
        "South Korea": "Korean",
        "Vietnam": "Vietnamese",
        "Hungary": "Hungarian",
        "Finland": "Finnish",
        "India": "Hindi",
        "Norway": "Norwegian",
        "Catalonia": "Catalan",
        "Thailand": "Thai",
        "Greece": "Greek",
        "Bangladesh": "Bengali",
        "Romania": "Romanian",
        "Serbia": "Serbian",
        "Denmark": "Danish",
        "Bulgaria": "Bulgarian",
        "Malaysia": "Malay",
        "Azerbaijan": "Azerbaijani",
        "Estonia": "Estonian",
        "Slovakia": "Slovak",
        "Armenia": "Armenian",
        "Uzbekistan": "Uzbek",
        "Croatia": "Croatian",
        "Basque Country": "Basque",
        "Slovenia": "Slovene",
        "Lithuania": "Lithuanian",
        "Latvia": "Latvian",
        "Esperanto": "Esperanto",
        "Belarus": "Belarusian",
        "Pakistan": "Urdu",
        "Kazakhstan": "Kazakh",
        "Tamil Nadu": "Tamil",
        "Georgia": "Georgian",
    }
    norp_country = {
        "English": "England",
        "British": "England",
        "German": "Germany",
        "French": "France",
        "Spanish": "Spain",
        "Japanese": "Japan",
        "Russian": "Russia",
        "Latn": "Portugal",
        "Italian": "Italy",
        "Chinese": "China",
        "Sichuan": "China",
        "Persian": "Iran",
        "Polish": "Poland",
        "Dutch": "Netherlands",
        "Arabian": "Arab World",
        "Ukrainian": "Ukraine",
        "Hebrew": "Israel",
        "Jewish": "Israel",
        "Israelite": "Israel",
        "Turkish": "Turkey",
        "Indonesian": "Indonesia",
        "Czech": "Czech Republic",
        "Swedish": "Sweden",
        "Korean": "South Korea",
        "Vietnamese": "Vietnam",
        "Hungarian": "Hungary",
        "Finnish": "Finland",
        "Hindi": "India",
        "Indian": "India",
        "Norwegian": "Norway",
        "Catalan": "Catalonia",
        "Thai": "Thailand",
        "Greek": "Greece",
        "Bengali": "Bangladesh",
        "Romanian": "Romania",
        "Serbian": "Serbia",
        "Danish": "Denmark",
        "Bulgarian": "Bulgaria",
        "Malay": "Malaysia",
        "Malaysian": "Malaysia",
        "Azerbaijani": "Azerbaijan",
        "Estonian": "Estonia",
        "Slovak": "Slovakia",
        "Slovakian": "Slovakia",
        "Armenian": "Armenia",
        "Uzbek": "Uzbekistan",
        "Croatian": "Croatia",
        "Basque": "Basque Country",
        "Slovene": "Slovenia",
        "Lithuanian": "Lithuania",
        "Latvian": "Latvia",
        "Esperanto": "Esperanto",
        "Belarusian": "Belarus",
        "Urdu": "Pakistan",
        "Kazakh": "Kazakhstan",
        "Tamil": "Tamil Nadu",
        "Georgian": "Georgia",
    }

    world_countries = {
        'Africa': ['Algeria', 'Angola', 'Benin', 'Botswana', 'Burkina Faso', 'Burundi', 'Cameroon', 'Cape Verde',
                   'Central African Republic', 'Chad', 'Comoros', 'Democratic Republic of the Congo', 'Djibouti',
                   'Egypt', 'Equatorial Guinea', 'Eritrea', 'Eswatini', 'Ethiopia', 'Gabon', 'Gambia', 'Ghana',
                   'Guinea', 'Guinea-Bissau', 'Ivory Coast', 'Kenya', 'Lesotho', 'Liberia', 'Libya', 'Madagascar',
                   'Malawi', 'Mali', 'Mauritania', 'Mauritius', 'Morocco', 'Mozambique', 'Namibia', 'Niger', 'Nigeria',
                   'Rwanda', 'Sao Tome and Principe', 'Senegal', 'Seychelles', 'Sierra Leone', 'Somalia',
                   'South Africa', 'South Sudan', 'Sudan', 'Tanzania', 'Togo', 'Tunisia', 'Uganda', 'Zambia',
                   'Zimbabwe'],
        'Asia': ['Afghanistan', 'Bahrain', 'Bangladesh', 'Bhutan', 'Brunei', 'Cambodia', 'China', 'India', 'Indonesia',
                 'Iran', 'Iraq', 'Israel', 'Japan', 'Jordan', 'Kazakhstan', 'Kuwait', 'Kyrgyzstan', 'Laos', 'Lebanon',
                 'Malaysia', 'Maldives', 'Mongolia', 'Myanmar', 'Nepal', 'North Korea', 'Oman', 'Pakistan', 'Palestine',
                 'Philippines', 'Qatar', 'Saudi Arabia', 'Singapore', 'South Korea', 'Sri Lanka', 'Syria', 'Taiwan',
                 'Tajikistan', 'Thailand', 'Timor-Leste', 'Turkey', 'Turkmenistan', 'United Arab Emirates',
                 'Uzbekistan', 'Vietnam', 'Yemen'],
        'Europe': ['Albania', 'Andorra', 'Armenia', 'Austria', 'Azerbaijan', 'Belarus', 'Belgium',
                   'Bosnia and Herzegovina', 'Bulgaria', 'Croatia', 'Cyprus', 'Czech Republic', 'Denmark', 'Estonia',
                   'Finland', 'France', 'Georgia', 'Germany', 'Greece', 'Hungary', 'Iceland', 'Ireland', 'Italy',
                   'Kazakhstan', 'Kosovo', 'Latvia', 'Liechtenstein', 'Lithuania', 'Luxembourg', 'Malta', 'Moldova',
                   'Monaco', 'Montenegro', 'Netherlands', 'North Macedonia', 'Norway', 'Poland', 'Portugal', 'Romania',
                   'Russia', 'San Marino', 'Serbia', 'Slovakia', 'Slovenia', 'Spain', 'Sweden', 'Switzerland',
                   'Ukraine', 'United Kingdom', 'Vatican City'],
        'North America': ['Antigua and Barbuda', 'Bahamas', 'Barbados', 'Belize', 'Canada', 'Costa Rica', 'Cuba',
                          'Dominica', 'Dominican Republic', 'El Salvador', 'Grenada', 'Guatemala', 'Haiti', 'Honduras',
                          'Jamaica', 'Mexico', 'Nicaragua', 'Panama', 'Saint Kitts and Nevis', 'Saint Lucia',
                          'Saint Vincent and the Grenadines', 'Trinidad and Tobago', 'United States'],
        'Oceania': ['Australia', 'Fiji', 'Kiribati', 'Marshall Islands', 'Micronesia', 'Nauru', 'New Zealand', 'Palau',
                    'Papua New Guinea', 'Samoa', 'Solomon Islands', 'Tonga', 'Tuvalu', 'Vanuatu'],
        'South America': ['Argentina', 'Bolivia', 'Brazil', 'Chile', 'Colombia', 'Ecuador', 'Guyana', 'Paraguay',
                          'Peru', 'Suriname', 'Uruguay', 'Venezuela'],
        'Mediterranean': ['Albania', 'Bosnia and Herzegovina', 'Croatia', 'Cyprus', 'Greece', 'Italy', 'Malta',
                          'Montenegro', 'Slovenia', 'Spain'],
        'Middle_Eastern': ['Bahrain', 'Iran', 'Iraq', 'Israel', 'Jordan', 'Kuwait', 'Lebanon', 'Oman', 'Palestine',
                           'Qatar', 'Saudi Arabia', 'Syria', 'Turkey', 'United Arab Emirates', 'Yemen']
    }

    languages_countries = create_languages_countries(
        countries_languages=countries_languages)

    def __init__(self, name: str):
        self.name = name
        # init lang
        self.lang = Country.countries_languages[name]
        # make lang unique
        self.lang = self.get_unique_lang()
        self.wiki_code = Country.languages_wiki[self.lang]

    def get_unique_lang(self) -> str:
        # because there are synonyms in the languages like british, english, etc., the languages can be
        # counted as different. Therefore a double mapping makes the language unique
        country = Country.languages_countries[self.lang][0]
        return Country.countries_languages[country]

    def __eq__(self, other):
        return isinstance(other, Country) and self.name == other.name

    def __hash__(self):
        return hash((self.name, self.lang, self.wiki_code))

    def get_wiki_code(self):
        Country.languages_wiki[self.lang]
