# from project.objects.receipe import Receipe
import spacy
import sys

# needs download of en_core_web_sm from spacy
# python -m spacy download en_core_web_sm


class Receipe:
    def __init__(self, title: str, description: str, origin: str, wiki_description: str, labels: list[str]):
        self.title = title
        self.description = description
        self.origin = origin
        self.wiki_description = wiki_description
        self.labels = labels

    def print(self):
        print('##################################################')
        print(f'Receipe: {self.title}')
        print(f'Description: {self.description}')
        print(f'Origin: {self.origin}')
        print(f'Wiki Description: {self.wiki_description}')
        print(f'Labels: {self.labels}')
        print('##################################################')


all_languages_wikipedia = {
    "English": "en",
    "German": "de",
    "French": "fr",
    "Spanish": "es",
    "Japanese": "ja",
    "Russian": "ru",
    "Latn": "pt",
    "Italien": "it",
    "Chinese": "zh",
    "Persian": "fa",
    "Polish": "pl",
    "Dutch": "nl",
    "Arabic": "ar",
    "Ukrainian": "uk",
    "Hebrew": "he",
    "Turkish": "tr",
    "Indonesian": "id",
    "Czech": "cs",
    "Swedish": "sv",
    "Korean": "ko",
    "Vietnamese": "vi",
    "Hungarian": "hu",
    "Finnish": "fi",
    "Hindi": "hi",
    "Norwegian": "no",
    "Catalan": "ca",
    "Thai": "th",
    "Greek": "el",
    "Bengali": "bn",
    "Romanian": "ro",
    "Serbian": "sr",
    "Danish": "da",
    "Bulgarian": "bg",
    "Malay": "ms",
    "Azerbaijani": "az",
    "Estonian": "et",
    "Slovak": "sk",
    "Armenian": "hy",
    "Uzbek": "uz",
    "Croatian": "hr",
    "Basque": "eu",
    "Slovene": "sl",
    "Lithuanian": "lt",
    "Latvian": "lv",
    "Esperanto": "eo",
    "Belarusian": "be",
    "Urdu": "ur",
    "Kazakh": "kk",
    "Tamil": "ta",
    "Georgian": "ka",
    "Galician": "gl",
    "Albanian": "sq",
    "Malayalam": "ml",
    "Hausa": "ha",
    "Macedonian": "mk",
    "Kannada": "kn",
    "Egyptian Arabic": "arz",
    "Serbo-Croatian": "sh",
    "Telugu": "te",
    "Cebuano": "ceb",
    "Afrikaans": "af",
    "Bosnian": "bs",
    "Marathi": "mr",
    "Sorani Kurdish": "ckb",
    "Icelandic": "is",
    "Norwegian (Nynorsk)": "nn",
    "Latin": "la",
    "Kyrgyz": "ky",
    "Tagalog": "tl",
    "Belarusian (Classical)": "be-tarask",
    "Mongolian": "mn",
    "Sanskrit": "sa",
    "Swahili": "sw",
    "Burmese": "my",
    "Punjabi": "pa",
    "Asturian": "ast",
    "Welsh": "cy",
    "Nepali": "ne",
    "Assamese": "as",
    "South Azerbaijani": "azb",
    "Kurdish (Kurmanji)": "ku",
    "Occitan": "oc",
    "Tajik": "tg",
    "Breton": "br",
    "Javanese": "jv",
    "Alemannic": "als",
    "Irish": "ga",
    "Scots": "sco",
    "Luxembourgish": "lb",
    "West Frisian": "fy",
    "Tatar": "tt",
    "Sinhala": "si",
    "Gujarati": "gu",
    "Somali": "so",
    "Odia": "or",
    "Yoruba": "yo",
    "Western Punjabi": "pnb",
    "Waray": "war",
    "Yiddish": "yi",
    "Haitian Creole": "ht",
    "Igbo": "ig",
    "Aragonese": "an",
    "Bashkir": "ba",
    "Classical Chinese": "zh-classical",
    "Khmer": "km",
    "Minangkabau": "min",
    "Ido": "io",
    "Moroccan Arabic": "ary",
    "Bavarian": "bar",
    "Chechen": "ce",
    "Pashto": "ps",
    "Lombard": "lmo",
    "Chuvash": "cv",
    "Kinyarwanda": "rw",
    "Amharic": "am",
    "Interlingua": "ia",
    "Central Bikol": "bcl",
    "Malagasy": "mg",
    "Maltese": "mt",
    "Wu Chinese": "wuu",
    "Silesian": "szl",
    "Old English": "ang",
    "Balinese": "ban",
    "Bhojpuri": "bh",
    "Sicilian": "scn",
    "Faroese": "fo",
    "Mazanderani": "mzn",
    "Quechua": "qu",
    "Low German": "nds",
    "Sundanese": "su",
    "Maithili": "mai",
    "Upper Sorbian": "hsb",
    "Mingrelian": "xmf",
    "Abkhaz": "ab",
    "Lao": "lo",
    "Tibetan": "bo",
    "Gorontalo": "gor",
    "Neapolitan": "nap",
    "Venetian": "vec",
    "Banjarese": "bjn",
    "Corsican": "co",
    "Gan Chinese": "gan",
    "Kapampangan": "pam",
    "Rusyn": "rue",
    "Turkmen": "tk",
    "Limburgish": "li",
    "Talysh": "tly",
    "Yakut": "sah",
    "Oromo": "om",
    "Guarani": "gn",
    "Dagbani": "dag",
    "Interlingue": "ie",
    "Volapük": "vo",
    "Western Armenian": "hyw",
    "Kabyle": "kab",
    "Twi": "tw",
    "Walloon": "wa",
    "Judaeo-Spanish": "lad",
    "Scottish Gaelic": "gd",
    "Eastern Min": "cdo",
    "Fula": "ff",
    "Extremaduran": "ext",
    "Ladin": "lld",
    "Ossetian": "os",
    "Hakka Chinese": "hak",
    "Karakalpak": "kaa",
    "Kashubian": "csb",
    "Lingua Franca Nova": "lfn",
    "Saraiki": "skr",
    "Uyghur": "ug",
    "Zazaki": "diq",
    "Meadow Mari": "mhr",
    "Papiamento": "pap",
    "Veps": "vep",
    "West Flemish": "vls",
    "Dutch Low Saxon": "nds-nl",
    "Samogitian": "bat-smg",
    "Cree": "cr",
    "Kotava": "avk",
    "Mirandese": "mwl",
    "North Frisian": "frr",
    "Old Church Slavonic": "cu",
    "Tulu": "tcy",
    "Dzongkha": "dz",
    "Newar": "new",
    "Picard": "pcd",
    "Banyumasan": "map-bms",
    "Hawaiian": "haw",
    "Ilocano": "ilo",
    "Komi": "kv",
    "Ligurian": "lij",
    "Sardinian": "sc",
    "Tyap": "kcg",
    "Aymara": "ay",
    "Maldivian": "dv",
    "Northern Sámi": "se",
    "Tuvan": "tyv",
    "Emilian-Romagnol": "eml",
    "Inuktitut": "iu",
    "Nigerian Pidgin": "pcm",
    "Tumbuka": "tum",
    "Udmurt": "udm",
    "Buginese": "bug",
    "Ingush": "inh",
    "Kabiye": "kbp",
    "Lingala": "ln",
    "Lower Sorbian": "dsb",
    "Shona": "sn",
    "Avar": "av",
    "Bishnupriya Manipuri": "bpy",
    "Franco-Provençal": "frp",
    "Gilaki": "glk",
    "Māori": "mi",
    "Tarantino": "roa-tara",
    "Tigrinya": "ti",
    "Tok Pisin": "tpi",
    "Aromanian": "roa-rup",
    "Buryat": "bxr",
    "Cornish": "kw",
    "Ewe": "ee",
    "Friulian": "fur",
    "Gagauz": "gag",
    "Inari Sámi": "smn",
    "Norfuk": "pih",
    "Norman": "nrm",
    "Pangasinan": "pag",
    "Xhosa": "xh",
    "Zeelandic": "zea",
    "Kashmiri": "ks",
    "Atayal": "tay",
    "Atikamekw": "atj",
    "Erzya": "myv",
    "Fon": "fon",
    "Kalmyk": "xal",
    "Kirundi": "rn",
    "Lezgian": "lez",
    "Livvi-Karelian": "olo",
    "Manx": "gv",
    "Meitei": "mni",
    "Nahuatl": "nah",
    "Pa'O": "blk",
    "Shan": "shn",
    "Shilha": "shi",
    "Awadhi": "awa",
    "Cherokee": "chr",
    "Hill Mari": "mrj",
    "Kabardian": "kbd",
    "Moksha": "mdf",
    "Romani": "rmy",
    "Romansh": "rm",
    "Sakizaya": "szy",
    "Konkani": "gom",
    "Gothic": "got",
    "Karachay-Balkar": "krc",
    "N'Ko": "nqo",
    "Palatine German": "pfl",
    "Pennsylvania Dutch": "pdc",
    "Ripuarian": "ksh",
    "Amis": "ami",
    "Doteli": "dty",
    "Komi-Permyak": "koi",
    "Latgalian": "ltg",
    "Mon": "mnw",
    "Northern Sotho": "nso",
    "Southern Altai": "alt",
    "Zhuang": "za",
    "Wolof": "wo",
    "Adyghe": "ady",
    "Chamorro": "ch",
    "Fante": "fat",
    "Iñupiaq": "ik",
    "Lojban": "jbo",
    "Navajo": "nv",
    "Sotho": "st",
    "Tongan": "to",
    "Võro": "fiu-vro",
    "Bambara": "bm",
    "Aramaic": "arc",
    "Ghanaian Pidgin": "gpe",
    "Gun": "guw",
    "Jamaican Patois": "jam",
    "Kikuyu": "ki",
    "Lak": "lbe",
    "Madurese": "mad",
    "Novial": "nov",
    "Saterland Frisian": "stq",
    "Angika": "anp",
    "Bislama": "bi",
    "Chewa": "ny",
    "Gurene": "gur",
    "Kongo": "kg",
    "Luganda": "lg",
    "Nias": "nia",
    "Pontic": "pnt",
    "Samoan": "sm",
    "Seediq": "trv",
    "Swazi": "ss",
    "Tswana": "tn",
    "Chavacano": "cbk-zam",
    "Guianan Creole": "gcr",
    "Pali": "pi",
    "Tetum": "tet",
    "Greenlandic": "kl",
    "Sranan Tongo": "srn",
    "Paiwan": "pwn",
    "Venda": "ve",
    "Dinka": "din",
    "Fijian": "fj",
    "Sango": "sg",
    "Tahitian": "ty",
    "Tsonga": "ts",
    "Cheyenne": "chy",
    "Wayuu": "guc",
    "Cantonese": "zh-yue",
    "Southern Min": "zh-min-nan"
}

top_h_languages_wikipedia = {
    "English": "en",
    "German": "de",
    "French": "fr",
    "Spanish": "es",
    "Japanese": "ja",
    "Russian": "ru",
    "Latn": "pt",
    "Italien": "it",
    "Chinese": "zh",
    "Persian": "fa",
    "Polish": "pl",
    "Dutch": "nl",
    "Arabic": "ar",
    "Ukrainian": "uk",
    "Hebrew": "he",
    "Turkish": "tr",
    "Indonesian": "id",
    "Czech": "cs",
    "Swedish": "sv",
    "Korean": "ko",
    "Vietnamese": "vi",
    "Hungarian": "hu",
    "Finnish": "fi",
    "Hindi": "hi",
    "Norwegian": "no",
    "Catalan": "ca",
    "Thai": "th",
    "Greek": "el",
    "Bengali": "bn",
    "Romanian": "ro",
    "Serbian": "sr",
    "Danish": "da",
    "Bulgarian": "bg",
    "Malay": "ms",
    "Azerbaijani": "az",
    "Estonian": "et",
    "Slovak": "sk",
    "Armenian": "hy",
    "Uzbek": "uz",
    "Croatian": "hr",
    "Basque": "eu",
    "Slovene": "sl",
    "Lithuanian": "lt",
    "Latvian": "lv",
    "Esperanto": "eo",
    "Belarusian": "be",
    "Urdu": "ur",
    "Kazakh": "kk",
    "Tamil": "ta",
    "Georgian": "ka",
    "Galician": "gl",
    "Albanian": "sq",
    "Malayalam": "ml",
    "Hausa": "ha",
    "Macedonian": "mk",
    "Kannada": "kn",
    "Egyptian Arabic": "arz",
    "Serbo-Croatian": "sh",
    "Telugu": "te",
    "Cebuano": "ceb",
    "Afrikaans": "af",
    "Bosnian": "bs",
    "Marathi": "mr",
    "Sorani Kurdish": "ckb",
    "Icelandic": "is",
    "Norwegian (Nynorsk)": "nn",
    "Latin": "la",
    "Kyrgyz": "ky",
    "Tagalog": "tl",
    "Belarusian (Classical)": "be-tarask",
    "Mongolian": "mn",
    "Sanskrit": "sa",
    "Swahili": "sw",
    "Burmese": "my",
    "Punjabi": "pa",
    "Asturian": "ast",
    "Welsh": "cy",
    "Nepali": "ne",
    "Assamese": "as",
    "South Azerbaijani": "azb",
    "Kurdish (Kurmanji)": "ku",
    "Occitan": "oc",
    "Tajik": "tg",
    "Breton": "br",
    "Javanese": "jv",
    "Alemannic": "als",
    "Irish": "ga",
    "Scots": "sco",
    "Luxembourgish": "lb",
    "West Frisian": "fy",
    "Tatar": "tt",
    "Sinhala": "si",
    "Gujarati": "gu",
    "Somali": "so",
    "Odia": "or",
    "Yoruba": "yo",
    "Western Punjabi": "pnb",
    "Waray": "war",
    "Yiddish": "yi",
    "Haitian Creole": "ht",
    "Igbo": "ig",
    "Aragonese": "an",
    "Bashkir": "ba",
    "Classical Chinese": "zh-classical",
    "Khmer": "km",
    "Minangkabau": "min",
    "Ido": "io",
    "Moroccan Arabic": "ary",
    "Bavarian": "bar",
    "Chechen": "ce",
    "Pashto": "ps",
    "Lombard": "lmo",
    "Chuvash": "cv",
    "Kinyarwanda": "rw",
    "Amharic": "am",
    "Interlingua": "ia",
    "Central Bikol": "bcl",
    "Malagasy": "mg",
    "Maltese": "mt",
    "Wu Chinese": "wuu",
    "Silesian": "szl",
    "Old English": "ang",
    "Balinese": "ban",
    "Bhojpuri": "bh",
    "Sicilian": "scn",
    "Faroese": "fo",
    "Mazanderani": "mzn",
    "Quechua": "qu",
    "Low German": "nds",
    "Sundanese": "su",
    "Maithili": "mai",
    "Upper Sorbian": "hsb",
    "Mingrelian": "xmf",
    "Abkhaz": "ab",
    "Lao": "lo",
    "Tibetan": "bo",
    "Gorontalo": "gor",
    "Neapolitan": "nap",
    "Venetian": "vec",
    "Banjarese": "bjn",
    "Corsican": "co",
    "Gan Chinese": "gan",
    "Kapampangan": "pam",
    "Rusyn": "rue",
    "Turkmen": "tk",
    "Limburgish": "li",
    "Talysh": "tly",
    "Yakut": "sah",
    "Oromo": "om",
    "Guarani": "gn",
    "Dagbani": "dag",
    "Interlingue": "ie",
    "Volapük": "vo",
    "Western Armenian": "hyw",
    "Kabyle": "kab",
    "Twi": "tw",
    "Walloon": "wa",
    "Judaeo-Spanish": "lad",
    "Scottish Gaelic": "gd",
    "Eastern Min": "cdo",
    "Fula": "ff",
    "Extremaduran": "ext",
    "Ladin": "lld",
    "Ossetian": "os",
    "Hakka Chinese": "hak",
    "Karakalpak": "kaa",
    "Kashubian": "csb",
}


class LabelExtractor:
    def __init__(self, receipe: Receipe):
        self.receipe = receipe

    def run(self) -> Receipe:
        nlp = spacy.load("en_core_web_sm")
        text = self.receipe.title + ". " + self.receipe.description
        text_nlp = nlp(text)

        entities = [ent.text for ent in text_nlp.ents]
        print(entities)
        updated_receipe = Receipe(
            self.receipe.title, self.receipe.description, "", "", [])

        return updated_receipe
